# Generated by Django 6.1 on 2026-08-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_remove_media_type_alter_media_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(default='Movie', max_length=50),
        ),
    ]
